# Homework 4

In [300]:
import pandas as pd
import sqlite3 as sql

## Joining Data

We want to analyse the number of cellphones per capita and to do so we need data on population sizes for countries in the years 1960-2020. This data can be loaded in through a csv-file named pop_data.csv.

In [303]:
pop_df = pd.read_csv('pop_data.csv')
pop_df

Unnamed: 0 iso-3         1960         1961         1962         1963  \
0             0   ABW      54608.0      55811.0      56682.0      57475.0   
1             1   AFE  130692579.0  134169237.0  137835590.0  141630546.0   
2             2   AFG    8622466.0    8790140.0    8969047.0    9157465.0   
3             3   AFW   97256290.0   99314028.0  101445032.0  103667517.0   
4             4   AGO    5357195.0    5441333.0    5521400.0    5599827.0   
..          ...   ...          ...          ...          ...          ...   
261         261   XKX     947000.0     966000.0     994000.0    1022000.0   
262         262   YEM    5542459.0    5646668.0    5753386.0    5860197.0   
263         263   ZAF   16520441.0   16989464.0   17503133.0   18042215.0   
264         264   ZMB    3119430.0    3219451.0    3323427.0    3431381.0   
265         265   ZWE    3806310.0    3925952.0    4049778.0    4177931.0   

            1964         1965         1966         1967         1968  \
0        58178.0      58782.0      59291.0      59522.0      59471.0   
1    145605995.0  149742351.0  153955516.0  158313235.0  162875171.0   
2      9355514.0    9565147.0    9783147.0   10010030.0   10247780.0   
3    105959979.0  108336203.0  110798486.0  113319950.0  115921723.0   
4      5673199.0    5736582.0    5787044.0    5827503.0    5868203.0   
..           ...          ...          ...          ...          ...   
261    1050000.0    1078000.0    1106000.0    1135000.0    1163000.0   
262    5973803.0    6097298.0    6228430.0    6368014.0    6515904.0   
263   18603097.0   19187194.0   19789771.0   20410677.0   21050540.0   
264    3542764.0    3658024.0    3777680.0    3901288.0    4029173.0   
265    4310332.0    4447149.0    4588529.0    4734694.0    4886347.0   

            1969         1970         1971         1972         1973  \
0        59330.0      59106.0      58816.0      58855.0      59365.0   
1    167596160.0  172475766.0  177503186.0  182599092.0  187901657.0   
2     10494489.0   10752971.0   11015857.0   11286753.0   11575305.0   
3    118615741.0  121424797.0  124336039.0  127364044.0  130563107.0   
4      5928386.0    6029700.0    6177049.0    6364731.0    6578230.0   
..           ...          ...          ...          ...          ...   
261    1191000.0    1219000.0    1247000.0    1278000.0    1308000.0   
262    6673981.0    6843607.0    7024196.0    7215835.0    7417736.0   
263   21704214.0   22368306.0   23031441.0   23698507.0   24382513.0   
264    4159007.0    4281671.0    4399919.0    4523581.0    4653289.0   
265    5044163.0    5202918.0    5363423.0    5532842.0    5712712.0   

            1974         1975         1976         1977         1978  \
0        60028.0      60715.0      61193.0      61465.0      61738.0   
1    193512956.0  199284304.0  205202669.0  211120911.0  217481420.0   
2     11869879.0   12157386.0   12425267.0   12687301.0   12938862.0   
3    133953892.0  137548613.0  141258400.0  145122851.0  149206663.0   
4      6802494.0    7032713.0    7266780.0    7511895.0    7771590.0   
..           ...          ...          ...          ...          ...   
261    1339000.0    1369000.0    1400000.0    1430000.0    1460000.0   
262    7630190.0    7855657.0    8094985.0    8348182.0    8615301.0   
263   25077016.0   25777964.0   26480300.0   27199838.0   27943445.0   
264    4789038.0    4931249.0    5079672.0    5233292.0    5391355.0   
265    5903530.0    6097083.0    6288387.0    6453044.0    6549349.0   

            1979         1980         1981         1982         1983  \
0        62006.0      62267.0      62614.0      63116.0      63683.0   
1    224315978.0  230967858.0  237937461.0  245386717.0  252779730.0   
2     12986369.0   12486631.0   11155195.0   10088289.0    9951449.0   
3    153459665.0  157825609.0  162323313.0  167023385.0  171566640.0   
4      8043218.0    8330047.0    8631457.0    8947152.0    9276707.0   
..           ...          ...          ...          .

We can look at which rows contain NaN so we know where to fill in values.

In [305]:
pop_nan_rows = pop_df[pop_df.isna().any(axis=1)]
pop_nan_rows

Unnamed: 0 iso-3  1960  1961  1962  1963  1964  1965  1966  1967  1968  \
110         110   INX   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
196         196   PSE   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   

     1969  1970  1971  1972  1973  1974  1975  1976  1977  1978  1979  1980  \
110   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
196   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   

     1981  1982  1983  1984  1985  1986  1987  1988  1989       1990  \
110   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN        NaN   
196   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  1978248.0   

          1991       1992       1993       1994       1995       1996  \
110        NaN        NaN        NaN        NaN        NaN        NaN   
196  2068845.0  2163591.0  2262676.0  2366298.0  2474666.0  2587997.0   

          1997       1998       1999       2000       2001       2002  \
110        NaN        NaN        NaN        NaN        NaN        NaN   
196  2706518.0  2776568.0  2848431.0  2922153.0  2997784.0  3075373.0   

          2003       2004       2005       2006       2007       2008  \
110        NaN        NaN        NaN        NaN        NaN        NaN   
196  3154969.0  3236626.0  3320396.0  3406334.0  3494496.0  3591977.0   

          2009       2010       2011       2012       2013       2014  \
110        NaN        NaN        NaN        NaN        NaN        NaN   
196  3689099.0  3786161.0  3882986.0  3979998.0  4076708.0  4173398.0   

          2015       2016       2017       2018       2019       2020  
110        NaN        NaN        NaN        NaN        NaN        NaN  
196  4270092.0  4367088.0  4454805.0  4569087.0  4685306.0  4803269.0

We can check if the row with index 110 only contains NaN values.

In [307]:
pd.isnull(pop_nan_rows.loc[110]).all()

False

Since the row with index 110 only contains NaN values we can not use forward- or backward fill directly. Instead we can fill the row succesively with the average values for each of the columns.

In [309]:
for year in range(1960, 2021):
    mean_year = pop_df[str(year)].mean()
    pop_df.loc[110, str(year)] = mean_year

pop_df.loc[110]

Unnamed: 0                 110
iso-3                      INX
1960          117271174.712121
1961          118880721.420455
1962          121051087.992424
1963          123733278.397727
1964          126437833.162879
1965          129181299.984848
1966          132040428.814394
1967          134898019.143939
1968          137835845.939394
1969          140878866.185606
1970          143969335.734848
1971          147116310.621212
1972          150211541.344697
1973          153350081.996212
1974          156475472.541667
1975          159536810.655303
1976          162568442.666667
1977          165589382.094697
1978          168665653.454545
1979          171826245.594697
1980          175014615.882576
1981           178281882.82197
1982          181701096.931818
1983          185149410.606061
1984          188588784.363636
1985          192101241.897727
1986          195717360.412879
1987               199432958.0
1988          203177006.174242
1989          206919900.962121
1990    

For the row with index 196 we can use backward fill since we have values in the later parts of the row.

In [311]:
pop_filled_df = pop_df.bfill(axis=1)
pop_filled_df.loc[196]

Unnamed: 0          196
iso-3               PSE
1960          1978248.0
1961          1978248.0
1962          1978248.0
1963          1978248.0
1964          1978248.0
1965          1978248.0
1966          1978248.0
1967          1978248.0
1968          1978248.0
1969          1978248.0
1970          1978248.0
1971          1978248.0
1972          1978248.0
1973          1978248.0
1974          1978248.0
1975          1978248.0
1976          1978248.0
1977          1978248.0
1978          1978248.0
1979          1978248.0
1980          1978248.0
1981          1978248.0
1982          1978248.0
1983          1978248.0
1984          1978248.0
1985          1978248.0
1986          1978248.0
1987          1978248.0
1988          1978248.0
1989          1978248.0
1990          1978248.0
1991          2068845.0
1992          2163591.0
1993          2262676.0
1994          2366298.0
1995          2474666.0
1996          2587997.0
1997          2706518.0
1998          2776568.0
1999          28

To join the previous cleaned cellphone data to our now filled population data we start by reading in the csv-file with the cellphone data.

In [313]:
df_cellphones = pd.read_csv('../HW3/cellphones.csv')
df_cellphones

Unnamed: 0 iso-3  1960  1965  1966  1967  1968  1969  1970  1971  1972  \
0             0   ABW   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
1             1   AFG   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
2             2   AGO   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
3             3   ALB   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
4             4   AND   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
5             5   ARE   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
6             6   ARG   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
7             7   ARM   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
8             8   ASM   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
9             9   ATG   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
10           10   AUS   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
11           11   AUT   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
12           12   AZE   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
13           13   BDI   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
14           14   BEL   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
15           15   BEN   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
16           16   BFA   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
17           17   BGD   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
18           18   BGR   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
19           19   BHR   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
20           20   BHS   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
21           21   BIH   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
22           22   BLR   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
23           23   BLZ   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
24           24   BMU   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
25           25   BOL   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
26           26   BRA   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
27           27   BRB   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
28           28   BRN   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
29           29   BTN   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
30           30   BWA   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
31           31   CAF   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
32           32   CAN   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
33           33   CHE   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
34           34   CHL   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
35           35   CHN   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
36           36   CIV   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
37           37   CMR   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
38           38   COD   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
39           39   COG   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
40           40   COL   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
41           41   COM   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
42           42   CPV   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
43           43   CRI   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
44           44   CUB   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
45           45   CUW   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
46           46   CYM   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
47           47   CYP   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
48           48   CZE   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
49           49   DEU   0.0   0.0   0.0   0.0   0.0   0

Since the cellphone dataframe has all rows and columns of the population dataframe but not the other way around we can do a left join on the cellphone dataframe. In this case we only want the top 5 countries alphabetically from the cellphones data and we want to combine it in a dataframe with columns for number of cellphones and size of population in the year 1960.

In [315]:
df_cellphones_first_5_countries_1960 = df_cellphones[['iso-3', '1960']].set_index('iso-3').head()
df_cellphones_first_5_countries_1960.rename(columns={'1960': 'n_cellphones_year_1960'}, inplace = True)
df_cellphones_first_5_countries_1960

n_cellphones_year_1960
iso-3                        
ABW                       0.0
AFG                       0.0
AGO                       0.0
ALB                       0.0
AND                       0.0

In [316]:
pop_filled_1960_df = pop_filled_df[['iso-3', '1960']].set_index('iso-3')
pop_filled_1960_df.rename(columns={'1960': 'population'}, inplace = True)
pop_filled_1960_df

population
iso-3             
ABW        54608.0
AFE    130692579.0
AFG      8622466.0
AFW     97256290.0
AGO      5357195.0
...            ...
XKX       947000.0
YEM      5542459.0
ZAF     16520441.0
ZMB      3119430.0
ZWE      3806310.0

[266 rows x 1 columns]

In [317]:
df_cellphones_first_5_countries_1960.merge(pop_filled_1960_df, on='iso-3', how='left')

n_cellphones_year_1960 population
iso-3                                   
ABW                       0.0    54608.0
AFG                       0.0  8622466.0
AGO                       0.0  5357195.0
ALB                       0.0  1608800.0
AND                       0.0     9443.0

Now we want to sort the 5 countries with the most cellphones per capita in the year 2019 but using the full names of the countries. To do this we need to load in a csv-file containing the country names among other things.

In [319]:
country_df = pd.read_csv('country_data.csv')
country_df.rename(columns={'alpha-3': 'iso-3'}, inplace=True)

We start by joining all three tables.

In [321]:
df_cellp_pop_countr_merge = df_cellphones \
    .merge(pop_filled_df, on='iso-3', how='left') \
    .merge(country_df, on='iso-3', how='left')

In [322]:
pd.set_option('display.max_columns', 200)

In [323]:
df_cellp_pop_countr_merge

Unnamed: 0_x iso-3  1960_x  1965_x  1966_x  1967_x  1968_x  1969_x  \
0               0   ABW     0.0     0.0     0.0     0.0     0.0     0.0   
1               1   AFG     0.0     0.0     0.0     0.0     0.0     0.0   
2               2   AGO     0.0     0.0     0.0     0.0     0.0     0.0   
3               3   ALB     0.0     0.0     0.0     0.0     0.0     0.0   
4               4   AND     0.0     0.0     0.0     0.0     0.0     0.0   
5               5   ARE     0.0     0.0     0.0     0.0     0.0     0.0   
6               6   ARG     0.0     0.0     0.0     0.0     0.0     0.0   
7               7   ARM     0.0     0.0     0.0     0.0     0.0     0.0   
8               8   ASM     0.0     0.0     0.0     0.0     0.0     0.0   
9               9   ATG     0.0     0.0     0.0     0.0     0.0     0.0   
10             10   AUS     0.0     0.0     0.0     0.0     0.0     0.0   
11             11   AUT     0.0     0.0     0.0     0.0     0.0     0.0   
12             12   AZE     0.0     0.0     0.0     0.0     0.0     0.0   
13             13   BDI     0.0     0.0     0.0     0.0     0.0     0.0   
14             14   BEL     0.0     0.0     0.0     0.0     0.0     0.0   
15             15   BEN     0.0     0.0     0.0     0.0     0.0     0.0   
16             16   BFA     0.0     0.0     0.0     0.0     0.0     0.0   
17             17   BGD     0.0     0.0     0.0     0.0     0.0     0.0   
18             18   BGR     0.0     0.0     0.0     0.0     0.0     0.0   
19             19   BHR     0.0     0.0     0.0     0.0     0.0     0.0   
20             20   BHS     0.0     0.0     0.0     0.0     0.0     0.0   
21             21   BIH     0.0     0.0     0.0     0.0     0.0     0.0   
22             22   BLR     0.0     0.0     0.0     0.0     0.0     0.0   
23             23   BLZ     0.0     0.0     0.0     0.0     0.0     0.0   
24             24   BMU     0.0     0.0     0.0     0.0     0.0     0.0   
25             25   BOL     0.0     0.0     0.0     0.0     0.0     0.0   
26             26   BRA     0.0     0.0     0.0     0.0     0.0     0.0   
27             27   BRB     0.0     0.0     0.0     0.0     0.0     0.0   
28             28   BRN     0.0     0.0     0.0     0.0     0.0     0.0   
29             29   BTN     0.0     0.0     0.0     0.0     0.0     0.0   
30             30   BWA     0.0     0.0     0.0     0.0     0.0     0.0   
31             31   CAF     0.0     0.0     0.0     0.0     0.0     0.0   
32             32   CAN     0.0     0.0     0.0     0.0     0.0     0.0   
33             33   CHE     0.0     0.0     0.0     0.0     0.0     0.0   
34             34   CHL     0.0     0.0     0.0     0.0     0.0     0.0   
35             35   CHN     0.0     0.0     0.0     0.0     0.0     0.0   
36             36   CIV     0.0     0.0     0.0     0.0     0.0     0.0   
37             37   CMR     0.0     0.0     0.0     0.0     0.0     0.0   
38             38   COD     0.0     0.0     0.0     0.0     0.0     0.0   
39             39   COG     0.0     0.0     0.0     0.0     0.0     0.0   
40             40   COL     0.0     0.0     0.0     0.0     0.0     0.0   
41             41   COM     0.0     0.0     0.0     0.0     0.0     0.0   
42             42   CPV     0.0     0.0     0.0     0.0     0.0     0.0   
43             43   CRI     0.0     0.0     0.0     0.0     0.0     0.0   
44             44   CUB     0.0     0.0     0.0     0.0     0.0     0.0   
45             45   CUW     0.0     0.0     0.0     0.0     0.0     0.0   
46             46   CYM     0.0     0.0     0.0     0.0     0.0     0.0   
47             47   CYP     0.0     0.0     0.0     0.0     0.0     0.0   
48             48   CZE     0.0     0.0     0.0     0.0     0.0     0.0   
49             49   DEU     0.0     0.0     0.0     0.0     0.0     0.0   
50             50   DJI     0.0     0.0     0.0     0.0     0.0     0.0   
51             51   DMA     0.0     0.0     0.0     0.0     0.0     0.0   
52             52   DNK     0.

In [324]:
df_cellp_pop_countr_merge['cellphones/capita'] = df_cellp_pop_countr_merge['2019_y'] / df_cellp_pop_countr_merge['2019_x']
df_cellphone_pop_countr_merge

Unnamed: 0_x iso-3  1960_x  1965_x  1966_x  1967_x  1968_x  1969_x  \
0               0   ABW     0.0     0.0     0.0     0.0     0.0     0.0   
1               1   AFG     0.0     0.0     0.0     0.0     0.0     0.0   
2               2   AGO     0.0     0.0     0.0     0.0     0.0     0.0   
3               3   ALB     0.0     0.0     0.0     0.0     0.0     0.0   
4               4   AND     0.0     0.0     0.0     0.0     0.0     0.0   
5               5   ARE     0.0     0.0     0.0     0.0     0.0     0.0   
6               6   ARG     0.0     0.0     0.0     0.0     0.0     0.0   
7               7   ARM     0.0     0.0     0.0     0.0     0.0     0.0   
8               8   ASM     0.0     0.0     0.0     0.0     0.0     0.0   
9               9   ATG     0.0     0.0     0.0     0.0     0.0     0.0   
10             10   AUS     0.0     0.0     0.0     0.0     0.0     0.0   
11             11   AUT     0.0     0.0     0.0     0.0     0.0     0.0   
12             12   AZE     0.0     0.0     0.0     0.0     0.0     0.0   
13             13   BDI     0.0     0.0     0.0     0.0     0.0     0.0   
14             14   BEL     0.0     0.0     0.0     0.0     0.0     0.0   
15             15   BEN     0.0     0.0     0.0     0.0     0.0     0.0   
16             16   BFA     0.0     0.0     0.0     0.0     0.0     0.0   
17             17   BGD     0.0     0.0     0.0     0.0     0.0     0.0   
18             18   BGR     0.0     0.0     0.0     0.0     0.0     0.0   
19             19   BHR     0.0     0.0     0.0     0.0     0.0     0.0   
20             20   BHS     0.0     0.0     0.0     0.0     0.0     0.0   
21             21   BIH     0.0     0.0     0.0     0.0     0.0     0.0   
22             22   BLR     0.0     0.0     0.0     0.0     0.0     0.0   
23             23   BLZ     0.0     0.0     0.0     0.0     0.0     0.0   
24             24   BMU     0.0     0.0     0.0     0.0     0.0     0.0   
25             25   BOL     0.0     0.0     0.0     0.0     0.0     0.0   
26             26   BRA     0.0     0.0     0.0     0.0     0.0     0.0   
27             27   BRB     0.0     0.0     0.0     0.0     0.0     0.0   
28             28   BRN     0.0     0.0     0.0     0.0     0.0     0.0   
29             29   BTN     0.0     0.0     0.0     0.0     0.0     0.0   
30             30   BWA     0.0     0.0     0.0     0.0     0.0     0.0   
31             31   CAF     0.0     0.0     0.0     0.0     0.0     0.0   
32             32   CAN     0.0     0.0     0.0     0.0     0.0     0.0   
33             33   CHE     0.0     0.0     0.0     0.0     0.0     0.0   
34             34   CHL     0.0     0.0     0.0     0.0     0.0     0.0   
35             35   CHN     0.0     0.0     0.0     0.0     0.0     0.0   
36             36   CIV     0.0     0.0     0.0     0.0     0.0     0.0   
37             37   CMR     0.0     0.0     0.0     0.0     0.0     0.0   
38             38   COD     0.0     0.0     0.0     0.0     0.0     0.0   
39             39   COG     0.0     0.0     0.0     0.0     0.0     0.0   
40             40   COL     0.0     0.0     0.0     0.0     0.0     0.0   
41             41   COM     0.0     0.0     0.0     0.0     0.0     0.0   
42             42   CPV     0.0     0.0     0.0     0.0     0.0     0.0   
43             43   CRI     0.0     0.0     0.0     0.0     0.0     0.0   
44             44   CUB     0.0     0.0     0.0     0.0     0.0     0.0   
45             45   CUW     0.0     0.0     0.0     0.0     0.0     0.0   
46             46   CYM     0.0     0.0     0.0     0.0     0.0     0.0   
47             47   CYP     0.0     0.0     0.0     0.0     0.0     0.0   
48             48   CZE     0.0     0.0     0.0     0.0     0.0     0.0   
49             49   DEU     0.0     0.0     0.0     0.0     0.0     0.0   
50             50   DJI     0.0     0.0     0.0     0.0     0.0     0.0   
51             51   DMA     0.0     0.0     0.0     0.0     0.0     0.0   
52             52   DNK     0.